global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets:
        - "api-0:8080"
        - "api-1:8080"
        - "api-2:8080"
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost"]
