// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package model

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Defines values for GameCondition.
const (
	Fair GameCondition = "fair"
	Good GameCondition = "good"
	Mint GameCondition = "mint"
	Poor GameCondition = "poor"
)

// Defines values for OfferStatus.
const (
	Accepted OfferStatus = "accepted"
	Pending  OfferStatus = "pending"
	Rejected OfferStatus = "rejected"
)

// Error defines model for Error.
type Error struct {
	Error string `json:"error,omitempty"`
}

// Game defines model for Game.
type Game struct {
	Condition *GameCondition      `bson:"condition,omitempty" json:"condition,omitempty"`
	Id        *primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	Name      *string             `bson:"name,omitempty" json:"name,omitempty"`
	OwnerId   *primitive.ObjectID `bson:"ownerId,omitempty" json:"ownerId,omitempty"`
	Publisher *string             `bson:"publisher,omitempty" json:"publisher,omitempty"`
}

// GameCondition defines model for Game.Condition.
type GameCondition string

// Message defines model for Message.
type Message struct {
	Message string `json:"Message,omitempty"`
}

// Offer defines model for Offer.
type Offer struct {
	GamesOffered   *[]primitive.ObjectID `bson:"gamesOffered,omitempty" json:"gamesOffered,omitempty"`
	GamesRequested *[]primitive.ObjectID `bson:"gamesRequested,omitempty" json:"gamesRequested,omitempty"`
	Id             *primitive.ObjectID   `bson:"_id,omitempty" json:"id,omitempty"`
	Offeree        *string               `bson:"offeree,omitempty" json:"offeree,omitempty"`
	Offeror        *string               `bson:"offeror,omitempty" json:"offeror,omitempty"`
	Status         OfferStatus           `bson:"status,omitempty" json:"status,omitempty"`
	Timestamp      openapi_types.Date    `bson:"timestamp,omitempty" json:"timestamp,omitempty"`
}

// OfferStatus defines model for Offer.Status.
type OfferStatus string

// User defines model for User.
type User struct {
	Address  *string             `bson:"address,omitempty" json:"address,omitempty"`
	Email    *string             `bson:"email,omitempty" json:"email,omitempty"`
	Id       *primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	Name     *string             `bson:"name,omitempty" json:"name,omitempty"`
	Password *string             `bson:"password,omitempty" json:"password,omitempty"`
}

// PostUsersIdChangePasswordJSONBody defines parameters for PostUsersIdChangePassword.
type PostUsersIdChangePasswordJSONBody struct {
	NewPassword *string `json:"newPassword,omitempty"`
}

// PostGamesJSONRequestBody defines body for PostGames for application/json ContentType.
type PostGamesJSONRequestBody = Game

// PatchGamesIdJSONRequestBody defines body for PatchGamesId for application/json ContentType.
type PatchGamesIdJSONRequestBody = Game

// PostOffersJSONRequestBody defines body for PostOffers for application/json ContentType.
type PostOffersJSONRequestBody = Offer

// PatchOffersIdJSONRequestBody defines body for PatchOffersId for application/json ContentType.
type PatchOffersIdJSONRequestBody = Offer

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// DeleteUsersIdJSONRequestBody defines body for DeleteUsersId for application/json ContentType.
type DeleteUsersIdJSONRequestBody = User

// PatchUsersIdJSONRequestBody defines body for PatchUsersId for application/json ContentType.
type PatchUsersIdJSONRequestBody = User

// PostUsersIdChangePasswordJSONRequestBody defines body for PostUsersIdChangePassword for application/json ContentType.
type PostUsersIdChangePasswordJSONRequestBody PostUsersIdChangePasswordJSONBody
